AddEventHandler("Phone:Server:RegisterCallbacks", function()
	exports["sandbox-base"]:RegisterServerCallback("Phone:Media:GetMedia", function(source, data, cb)
		cb(exports['sandbox-phone']:PhotosFetch(source))
	end)
	exports["sandbox-base"]:RegisterServerCallback("Phone:Media:DeleteMedia", function(source, data, cb)
		cb(exports['sandbox-phone']:PhotosDelete(source, data.id))
	end)
end)
