AddEventHandler("Phone:Server:RegisterCallbacks", function()
	exports["sandbox-base"]:RegisterServerCallback("Phone:Media:GetMedia", function(source, data, cb)
		cb(Photos:Fetch(source))
	end)
	exports["sandbox-base"]:RegisterServerCallback("Phone:Media:DeleteMedia", function(source, data, cb)
		cb(Photos:Delete(source, data.id))
	end)
end)
