-- AddEventHandler('Core:Shared:Ready', function()
--     exports["sandbox-chat"]:RegisterCommand('menu', function(source, args, rawCommand)
--         TriggerClientEvent('Menu:Client:Test', source)
--     end, {
--         help = 'Test Menu'
--     })
-- end)
