local repairPartRecipes = {
	["repair_part_electronics"] = {
		result = { name = "repair_part_electronics", count = 10 },
		items = {
			{ name = "electronic_parts", count = 5 },
			{ name = "plastic", count = 4 },
			{ name = "rubber", count = 1 },
			{ name = "copperwire", count = 8 },
		},
		time = 3500,
	},
	["repair_part_axle"] = {
		result = { name = "repair_part_axle", count = 5 },
		items = {
			{ name = "ironbar", count = 4 },
		},
		time = 5000,
	},
	["repair_part_injectors"] = {
		result = { name = "repair_part_injectors", count = 20 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "glue", count = 1 },
		},
		time = 4500,
	},
	["repair_part_clutch"] = {
		result = { name = "repair_part_clutch", count = 8 },
		items = {
			{ name = "ironbar", count = 6 },
			{ name = "rubber", count = 1 },
		},
		time = 5000,
	},
	["repair_part_brakes"] = {
		result = { name = "repair_part_brakes", count = 5 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "glue", count = 1 },
		},
		time = 4500,
	},
	["repair_part_transmission"] = {
		result = { name = "repair_part_transmission", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 1 },
			{ name = "plastic", count = 1 },
		},
		time = 3500,
	},
	["repair_part_rad"] = {
		result = { name = "repair_part_rad", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "rubber", count = 1 },
			{ name = "glue", count = 1 },
		},
		time = 2000,
	},

	-- High Grade
	["repair_part_injectors_hg"] = {
		result = { name = "repair_part_injectors_hg", count = 20 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "heavy_glue", count = 1 },
		},
		time = 11000,
	},
	["repair_part_clutch_hg"] = {
		result = { name = "repair_part_clutch_hg", count = 8 },
		items = {
			{ name = "ironbar", count = 8 },
			{ name = "rubber", count = 2 },
		},
		time = 13000,
	},
	["repair_part_brakes_hg"] = {
		result = { name = "repair_part_brakes_hg", count = 5 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "heavy_glue", count = 1 },
		},
		time = 9000,
	},
	["repair_part_transmission_hg"] = {
		result = { name = "repair_part_transmission_hg", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 1 },
			{ name = "plastic", count = 1 },
			{ name = "copperwire", count = 1 },
		},
		time = 9000,
	},
	["repair_part_rad_hg"] = {
		result = { name = "repair_part_rad_hg", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "rubber", count = 1 },
			{ name = "glue", count = 1 },
		},
		time = 6000,
	},
	["lockpick"] = {
		result = { name = "lockpick", count = 2 },
		items = {
			{ name = "ironbar", count = 5 },
			{ name = "scrapmetal", count = 10 },
		},
		time = 5000,
	},
	["adv_lockpick"] = {
		result = { name = "adv_lockpick", count = 4 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "scrapmetal", count = 40 },
			{ name = "diamond", count = 1 },
		},
		time = 5000,
	},
	["camber_controller"] = {
		result = { name = "camber_controller", count = 1 },
		items = {
			{ name = "plastic", count = 40 },
			{ name = "ironbar", count = 20 },
			{ name = "electronic_parts", count = 75 },
			{ name = "scrapmetal", count = 10 },
			{ name = "heavy_glue", count = 10 },
			{ name = "goldbar", count = 1 },
			{ name = "diamond", count = 1 },
		},
		time = 8000,
	},
	["fakeplates"] = {
		result = { name = "fakeplates", count = 2 },
		items = {
			{ name = "plastic", count = 1 },
			{ name = "scrapmetal", count = 1 },
		},
		time = 8000,
	},
	["repairkit"] = {
		result = { name = "repairkit", count = 4 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "glue", count = 1 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "rubber", count = 2 },
		},
		time = 3500,
	},
	["repairkitadv"] = {
		result = { name = "repairkitadv", count = 4 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "heavy_glue", count = 1 },
			{ name = "plastic", count = 3 },
			{ name = "copperwire", count = 4 },
			{ name = "rubber", count = 4 },
		},
		time = 5500,
	},
	["carclean"] = {
		result = { name = "carclean", count = 4 },
		items = {
			{ name = "water", count = 1 },
			{ name = "plastic", count = 4 },
		},
		time = 5500,
	},
	["upgrade_turbo"] = {
		result = { name = "upgrade_turbo", count = 1 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "copperwire", count = 150 },
			{ name = "electronic_parts", count = 75 },
			{ name = "rubber", count = 100 },
			{ name = "plastic", count = 100 },
			{ name = "goldbar", count = 5 },
			{ name = "silverbar", count = 5 },
			{ name = "heavy_glue", count = 50 },
			{ name = "diamond", count = 2 },
		},
		time = 2000,
	},
	["upgrade_engine1"] = {
		result = { name = "upgrade_engine1", count = 1 },
		items = {
			{ name = "ironbar", count = 5 },
			{ name = "copperwire", count = 30 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 45 },
			{ name = "silverbar", count = 1 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_engine2"] = {
		result = { name = "upgrade_engine2", count = 1 },
		items = {
			{ name = "ironbar", count = 10 },
			{ name = "copperwire", count = 50 },
			{ name = "electronic_parts", count = 50 },
			{ name = "rubber", count = 60 },
			{ name = "silverbar", count = 3 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_engine3"] = {
		result = { name = "upgrade_engine3", count = 1 },
		items = {
			{ name = "ironbar", count = 15 },
			{ name = "copperwire", count = 70 },
			{ name = "electronic_parts", count = 74 },
			{ name = "rubber", count = 80 },
			{ name = "goldbar", count = 5 },
			{ name = "silverbar", count = 5 },
		},
		time = 2000,
	},
	["upgrade_engine4"] = {
		result = { name = "upgrade_engine4", count = 1 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "copperwire", count = 90 },
			{ name = "electronic_parts", count = 100 },
			{ name = "rubber", count = 100 },
			{ name = "goldbar", count = 7 },
			{ name = "silverbar", count = 7 },
		},
		time = 2000,
	},
	["upgrade_brakes1"] = {
		result = { name = "upgrade_brakes1", count = 1 },
		items = {
			{ name = "ironbar", count = 5 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 45 },
			{ name = "glue", count = 30 },
			{ name = "silverbar", count = 1 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_brakes2"] = {
		result = { name = "upgrade_brakes2", count = 1 },
		items = {
			{ name = "ironbar", count = 10 },
			{ name = "electronic_parts", count = 50 },
			{ name = "rubber", count = 60 },
			{ name = "glue", count = 30 },
			{ name = "silverbar", count = 3 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_brakes3"] = {
		result = { name = "upgrade_brakes3", count = 1 },
		items = {
			{ name = "ironbar", count = 15 },
			{ name = "electronic_parts", count = 75 },
			{ name = "rubber", count = 80 },
			{ name = "glue", count = 40 },
			{ name = "silverbar", count = 5 },
			{ name = "goldbar", count = 5 },
		},
		time = 2000,
	},
	["upgrade_brakes4"] = {
		result = { name = "upgrade_brakes4", count = 1 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "electronic_parts", count = 100 },
			{ name = "rubber", count = 100 },
			{ name = "glue", count = 50 },
			{ name = "silverbar", count = 7 },
			{ name = "goldbar", count = 7 },
		},
		time = 2000,
	},
	["upgrade_transmission1"] = {
		result = { name = "upgrade_transmission1", count = 1 },
		items = {
			{ name = "ironbar", count = 5 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 15 },
			{ name = "plastic", count = 20 },
			{ name = "heavy_glue", count = 3 },
			{ name = "silverbar", count = 1 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_transmission2"] = {
		result = { name = "upgrade_transmission2", count = 1 },
		items = {
			{ name = "ironbar", count = 10 },
			{ name = "electronic_parts", count = 50 },
			{ name = "rubber", count = 30 },
			{ name = "plastic", count = 30 },
			{ name = "heavy_glue", count = 6 },
			{ name = "silverbar", count = 3 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_transmission3"] = {
		result = { name = "upgrade_transmission3", count = 1 },
		items = {
			{ name = "ironbar", count = 15 },
			{ name = "electronic_parts", count = 75 },
			{ name = "rubber", count = 45 },
			{ name = "plastic", count = 40 },
			{ name = "heavy_glue", count = 9 },
			{ name = "silverbar", count = 5 },
			{ name = "goldbar", count = 5 },
		},
		time = 2000,
	},
	["upgrade_transmission4"] = {
		result = { name = "upgrade_transmission4", count = 1 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "electronic_parts", count = 100 },
			{ name = "rubber", count = 60 },
			{ name = "plastic", count = 50 },
			{ name = "heavy_glue", count = 12 },
			{ name = "silverbar", count = 7 },
			{ name = "goldbar", count = 7 },
		},
		time = 2000,
	},
	["upgrade_suspension1"] = {
		result = { name = "upgrade_suspension1", count = 1 },
		items = {
			{ name = "ironbar", count = 5 },
			{ name = "copperwire", count = 20 },
			{ name = "rubber", count = 10 },
			{ name = "plastic", count = 10 },
			{ name = "glue", count = 15 },
			{ name = "silverbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_suspension2"] = {
		result = { name = "upgrade_suspension2", count = 1 },
		items = {
			{ name = "ironbar", count = 10 },
			{ name = "copperwire", count = 30 },
			{ name = "rubber", count = 20 },
			{ name = "plastic", count = 25 },
			{ name = "glue", count = 18 },
			{ name = "silverbar", count = 5 },
		},
		time = 2000,
	},
	["upgrade_suspension3"] = {
		result = { name = "upgrade_suspension3", count = 1 },
		items = {
			{ name = "ironbar", count = 15 },
			{ name = "copperwire", count = 40 },
			{ name = "rubber", count = 30 },
			{ name = "plastic", count = 40 },
			{ name = "glue", count = 21 },
			{ name = "goldbar", count = 7 },
		},
		time = 2000,
	},
	["upgrade_suspension4"] = {
		result = { name = "upgrade_suspension4", count = 1 },
		items = {
			{ name = "ironbar", count = 20 },
			{ name = "copperwire", count = 50 },
			{ name = "rubber", count = 40 },
			{ name = "plastic", count = 55 },
			{ name = "glue", count = 24 },
			{ name = "goldbar", count = 8 },
		},
		time = 2000,
	},
	["carpolish"] = {
		result = { name = "carpolish", count = 4 },
		items = {
			{ name = "fishing_oil", count = 1 },
			{ name = "plastic", count = 20 },
		},
		time = 1000,
	},
	["carpolish_high"] = {
		result = { name = "carpolish_high", count = 4 },
		items = {
			{ name = "fishing_oil", count = 2 },
			{ name = "plastic", count = 40 },
			{ name = "cloth", count = 20 },
		},
		time = 1000,
	},
}

_mechanicShopStorageCrafting = {
	{
		job = "redline",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-584.07, -939.57, 23.89),
						l = 1.0,
						w = 3.8,
						options = {
							heading = 270,
							--debugPoly=true,
							minZ = 23.29,
							maxZ = 24.89,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-589.19, -926.07, 28.14),
						l = 1.0,
						w = 2.0,
						options = {
							heading = 270,
							--debugPoly=true,
							minZ = 27.54,
							maxZ = 29.14,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "tuna",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(133.37, -3051.24, 7.04),
						w = 1.8,
						l = 11.8,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 6.04,
							maxZ = 8.24,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_turbo,
					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "tirenutz",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-57.5, -1325.07, 29.27),
						w = 4.2,
						l = 1.0,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 28.27,
							maxZ = 31.07,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "hayes",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-1421.67, -456.38, 35.91),
						w = 3.8,
						l = 1.0,
						options = {
							heading = 302,
							--debugPoly=true,
							minZ = 34.91,
							maxZ = 37.31,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},

	{
		job = "atomic",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(476.67, -1876.93, 26.09),
						w = 1.2,
						l = 4.0,
						options = {
							heading = 25,
							--debugPoly=true,
							minZ = 25.09,
							maxZ = 28.09,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "harmony",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(1176.15, 2635.21, 37.75),
						w = 3.8,
						l = 1.4,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 36.75,
							maxZ = 39.55,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "blackline",
		partCrafting = {
			-- {
			--     label = "Make Parts",
			--     targeting = {
			--         actionString = "Crafting",
			--         icon = "toolbox",
			--         poly = {
			--             coords = vector3(1176.15, 2635.21, 37.75),
			--             w = 3.8,
			--             l = 1.4,
			--             options = {
			--                 heading = 0,
			--                 --debugPoly=true,
			--                 minZ = 36.75,
			--                 maxZ = 39.55
			--             },
			--         },
			--     },
			--     recipes = {
			--         repairPartRecipes.repair_part_electronics,
			--         repairPartRecipes.repair_part_axle,
			--         repairPartRecipes.repair_part_injectors,
			--         repairPartRecipes.repair_part_clutch,
			--         repairPartRecipes.repair_part_brakes,
			--         repairPartRecipes.repair_part_transmission,
			--         repairPartRecipes.repair_part_rad,
			--         repairPartRecipes.repair_part_injectors_hg,
			--         repairPartRecipes.repair_part_clutch_hg,
			--         repairPartRecipes.repair_part_brakes_hg,
			--         repairPartRecipes.repair_part_transmission_hg,
			--         repairPartRecipes.repair_part_rad_hg,
			--         repairPartRecipes.lockpick,
			--         repairPartRecipes.adv_lockpick,
			--         repairPartRecipes.repairkit,
			--         repairPartRecipes.repairkitadv,
			--         repairPartRecipes.carclean,
			--     },
			-- },
		},
	},
	{
		job = "autoexotics",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(558.99, -171.67, 54.51),
						w = 1.2,
						l = 3.6,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 53.51,
							maxZ = 56.11,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "ottos",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(950.91, -979.09, 39.5),
						w = 3.8,
						l = 1.2,
						options = {
							heading = 4,
							--debugPoly=true,
							minZ = 38.55,
							maxZ = 40.75,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "bennys",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-205.3346, -1335.6605, 31.300),
						w = 1.0,
						l = 5.0,
						options = {
							heading = 270,
							--debugPoly = true,
							minZ = 29.300,
							maxZ = 32.300,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "paleto_tuners",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(163.12, 6364.78, 31.27),
						w = 2.0,
						l = 4.4,
						options = {
							heading = 30,
							--debugPoly=true,
							minZ = 30.27,
							maxZ = 32.67,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
	{
		job = "dreamworks",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-726.39, -1505.64, 5.06),
						w = 1.0,
						l = 5.0,
						options = {
							heading = 293,
							--debugPoly=true,
							minZ = 4.06,
							maxZ = 6.66,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.camber_controller,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					-- repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					-- repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					-- repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					-- repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,

					repairPartRecipes.carpolish,
					repairPartRecipes.carpolish_high,
				},
			},
		},
	},
}
